
export const listings = [
    {
        id: 1,
        name: 'Sunny Home',
        img: "src/images/Screenshot 2023-12-08 234038.png",
        address: "123 Main St",
        desc: "This is a very nice Home That was built in 1992 and has been well maintained. It has a nice view of the city and is close to the beach",
        longDesc: "This meticulously crafted home, a testament to timeless design, was expertly constructed in 1992 and has been impeccably maintained ever since. Nestled in a serene locale, it boasts an unparalleled view of the city skyline that adds an extra touch of elegance to its charm. The residence's classic architecture is complemented by modern amenities, creating a perfect blend of comfort and sophistication.As you step into this inviting abode, you'll be greeted by a warm ambiance that permeates every corner. The well-thought-out layout provides a seamless flow between rooms, making each space feel connected and purposeful. The living areas are bathed in natural light, creating a welcoming atmosphere for both relaxation and entertainment. One of the highlights of this home is its proximity to the beach, offering an escape to coastal tranquility just moments away. Whether you're savoring the picturesque views from the comfort of your own backyard or taking a leisurely stroll along the sandy shores, the beach becomes an extension of your lifestyle. The residence, surrounded by lush landscaping, provides a sense of privacy and seclusion while being conveniently located near amenities. From the thoughtfully designed interiors to the panoramic views of the cityscape, this home is a haven for those who appreciate the perfect blend of comfort, style, and a touch of coastal allure.",
    },
    {
        id: 2,
        name: 'Fun Home',
        img: "src/images/Screenshot 2023-12-08 234129.png",
        address: "321 South St",
        desc: "This is a very nice beautiful home That was built in 1995 and has been brand new. It has all the moden amenities that everyone wants in their dream home",
        longDesc: "Step into the lap of luxury with this stunning residence, a beautiful gem built in 1995 that still exudes the freshness of a brand-new home. Meticulously crafted with an unwavering commitment to quality, this residence stands as a testament to enduring elegance. From the moment you set foot inside, you'll be enveloped in a sense of opulence and sophistication. This architectural masterpiece seamlessly marries timeless design with the allure of modern living. The home's exterior exudes curb appeal, showcasing meticulous landscaping and a design that captivates from every angle. The interiors are a symphony of space and light, with large windows framing scenic views and filling each room with an abundance of natural sunshine. Every inch of this home has been thoughtfully curated to cater to contemporary tastes. The kitchen, a culinary haven, features top-of-the-line appliances, sleek countertops, and ample storage, making it a focal point for culinary enthusiasts and a hub for social gatherings. The living spaces, adorned with exquisite finishes, create an ambiance that effortlessly combines comfort and style. The year 1995 marks not just the construction of a home but the creation of a haven that has stood the test of time. Modern amenities, carefully integrated, elevate the living experience. From smart home features to spa-like bathrooms, this residence has everything one could desire in their dream home. Perfectly positioned, this home offers a tranquil retreat from the hustle and bustle, providing a sense of sanctuary while being conveniently located for easy access to amenities and entertainment. The exterior spaces are an extension of the luxury within, with meticulously landscaped gardens, a private oasis for relaxation, and perhaps even a pool to complete the dream. Indulge in the embodiment of timeless beauty and contemporary comfort with this exceptional residence. It's not just a home; it's a masterpiece where every detail has been considered, and every comfort awaits your arrival.",
    },
    {
        id: 3,
        name: 'Fixer Upper',
        img: "src/images/Screenshot 2023-12-08 234321.png",
        address: "456 1st St",
        desc: "This is a lovely home, that needs a bit of TLC. This home was built in 1997 and has great bones. It has a lot of potential to be a great home",
        longDesc: "Discover the potential of this charming residence, a lovely home with a story to tell. Constructed in 1997, this gem boasts great bones and a solid foundation, promising a canvas on which you can weave your dreams. While time may have left its gentle touch, this abode invites you to embark on a journey of restoration and transformation. Step into a home that exudes character, where each creaky floorboard and aged brick tells a tale of memories made and possibilities awaiting. The timeless architecture provides a solid framework, creating a foundation upon which you can craft a home uniquely yours. With a bit of creativity and a touch of inspiration, this residence has the potential to become a showcase of personalized style and character. While the home may require a bit of extra attention, envision the endearing details that can be uncovered with some tender loving care. Picture sunlit rooms adorned with vintage charm, each corner telling a story of your own design. The spacious layout allows for flexibility, offering the opportunity to reimagine spaces and breathe new life into every room. The year 1997 stands as a testament to enduring craftsmanship, and with your vision, this home can become a modern haven while retaining its classic appeal. The potential for restoration is boundless, from the revival of hardwood floors to the enhancement of architectural details that can be lovingly preserved. The surrounding grounds, with the right touch, can bloom into a private oasis, a testament to the transformative power of care and attention. Imagine enjoying lazy afternoons on a revitalized porch or hosting gatherings in a garden brought back to life with vibrant blooms and greenery. With the commitment to a little extra care, this home is poised to become not just a living space but a reflection of your personality and aspirations. Embrace the journey of restoration, and let this home be the canvas upon which you paint the story of your next chapter.",
    }
]